In [1]:
#  DataFrame.insert() -  Add Column to DataFrame

# assign()  - returns a new DataFrame after adding a column


# Create DataFrame
import pandas as pd
import numpy as np

technologies= {
    'Courses':["Spark","PySpark","Hadoop","Python","Pandas"],
    'Fee' :[22000,25000,23000,24000,26000],
    'Discount':[1000,2300,1000,1200,2500]
          }

df = pd.DataFrame(technologies)
print(df)

   Courses    Fee  Discount
0    Spark  22000      1000
1  PySpark  25000      2300
2   Hadoop  23000      1000
3   Python  24000      1200
4   Pandas  26000      2500

In [2]:

# Let’s add a column ‘TutorsAssigned” to the DataFrame using assign()

# Add new column to the DataFrame
tutors = ['William', 'Henry', 'Michael', 'John', 'Messi']
df2 = df.assign(TutorAssigned = tutors)
df2

   Courses    Fee  Discount TutorAssigned
0    Spark  22000      1000       William
1  PySpark  25000      2300         Henry
2   Hadoop  23000      1000       Michael
3   Python  24000      1200          John
4   Pandas  26000      2500         Messi

In [16]:
 # Add Multiple Columns to the DataFrame

MNCCompanies = ['Google', 'TCS', 'Tech Mahindra', 'Wipro', 'HCL']

df2 = df.assign(TutorAssigned = tutors, MNCComp = MNCCompanies, Address = np.nan)
df2

   Courses    Fee  Discount TutorAssigned        MNCComp  Address
0    Spark  22000      1000       William         Google      NaN
1  PySpark  25000      2300         Henry            TCS      NaN
2   Hadoop  23000      1000       Michael  Tech Mahindra      NaN
3   Python  24000      1200          John          Wipro      NaN
4   Pandas  26000      2500         Messi            HCL      NaN

In [14]:
# Adding a Column From Existing
# derives Discount_Percent column from Fee and Discount

df = pd.DataFrame(technologies)
df2 = df.assign(Discount_percent = lambda x: (x.Discount * 100) / x.Fee)
df2

   Courses    Fee  Discount  Discount_percent
0    Spark  22000      1000          4.545455
1  PySpark  25000      2300          9.200000
2   Hadoop  23000      1000          4.347826
3   Python  24000      1200          5.000000
4   Pandas  26000      2500          9.615385

In [ ]:
# Append Column to Existing Pandas DataFrame

In [17]:
df = pd.DataFrame(technologies)
df['MNCComp'] = MNCCompanies
df

   Courses    Fee  Discount        MNCComp
0    Spark  22000      1000         Google
1  PySpark  25000      2300            TCS
2   Hadoop  23000      1000  Tech Mahindra
3   Python  24000      1200          Wipro
4   Pandas  26000      2500            HCL

In [24]:
# Add Column to Specific Position of DataFrame
# DataFrame.insert() method is used to add DataFrame at any position of the existing DataFrame.


# Add Tutors column at the beginning of the DataFrame.

df = pd.DataFrame(technologies)
print(df)
print('')

df.insert(0, 'Tutor', tutors)

print('Added Tutors column at the beginning')
df

   Courses    Fee  Discount
0    Spark  22000      1000
1  PySpark  25000      2300
2   Hadoop  23000      1000
3   Python  24000      1200
4   Pandas  26000      2500

Added Tutors column at the beginning

     Tutor  Courses    Fee  Discount
0  William    Spark  22000      1000
1    Henry  PySpark  25000      2300
2  Michael   Hadoop  23000      1000
3     John   Python  24000      1200
4    Messi   Pandas  26000      2500