In [2]:

# Syntax of append()

# DataFrame.append(other, ignore_index=False, verify_integrity=False, sort=False)

# used to append one DataFrame row(s) and column(s) with another,

In [3]:

import pandas as pd

df = pd.DataFrame({'Courses': ["Spark","PySpark","Python","pandas"],
                    'Fee' : [20000,25000,22000,24000]})

df1 = pd.DataFrame({'Courses': ["Pandas","Hadoop","Hyperion","Java"],
                    'Fee': [25000,25200,24500,24900],
                    'Duration': ['30days','35days','40days','45days']})

# Using append() method
df2 = df.append(df1)
print(df2)

    Courses    Fee Duration
0     Spark  20000      NaN
1   PySpark  25000      NaN
2    Python  22000      NaN
3    pandas  24000      NaN
0    Pandas  25000   30days
1    Hadoop  25200   35days
2  Hyperion  24500   40days
3      Java  24900   45days

C:\Users\ak8184\AppData\Local\Temp\ipykernel_29356\3880735837.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df.append(df1)

In [4]:
# Reindex the DataFrame while Append
# ignore_index = True

df2 = df.append(df1, ignore_index = True)
df2

C:\Users\ak8184\AppData\Local\Temp\ipykernel_29356\2630856142.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df.append(df1, ignore_index = True)

    Courses    Fee Duration
0     Spark  20000      NaN
1   PySpark  25000      NaN
2    Python  22000      NaN
3    pandas  24000      NaN
4    Pandas  25000   30days
5    Hadoop  25200   35days
6  Hyperion  24500   40days
7      Java  24900   45days

In [5]:
# Create third DataFrame  
df2 = pd.DataFrame({'Courses':['PHP','GO'],
                    'Duration':['30day','40days'],
                    'Fee':[10000,23000]})
df3 = df.append([df1, df2], ignore_index = True)
df3

C:\Users\ak8184\AppData\Local\Temp\ipykernel_29356\120833020.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df.append([df1, df2], ignore_index = True)

    Courses    Fee Duration
0     Spark  20000      NaN
1   PySpark  25000      NaN
2    Python  22000      NaN
3    pandas  24000      NaN
4    Pandas  25000   30days
5    Hadoop  25200   35days
6  Hyperion  24500   40days
7      Java  24900   45days
8       PHP  10000    30day
9        GO  23000   40days