In [3]:
import pandas as pd

# create DataFrmae from a List

technologies = [['PySpark', 500000, '60 days'],
                ['Pandas', 40000, '30 days'],
                ['Python', 60000, '90 days']
               ]
df = pd.DataFrame(technologies)
df

         0       1        2
0  PySpark  500000  60 days
1   Pandas   40000  30 days
2   Python   60000  90 days

In [6]:
# create dataFrame with columns

column_names = ['Courses', 'Fee', 'Duration']
df1 = pd.DataFrame(data = technologies, columns = column_names)
df1

   Courses     Fee Duration
0  PySpark  500000  60 days
1   Pandas   40000  30 days
2   Python   60000  90 days

In [10]:
# create Empty DataFrame with columns

df = pd.DataFrame(columns = ['Skills','Exp', 'Rating'])
df
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Skills  0 non-null      object
 1   Exp     0 non-null      object
 2   Rating  0 non-null      object
dtypes: object(3)
memory usage: 0.0+ bytes

In [12]:
# create DataFrame from a Dict (Dictionary)

techs = {
        'Courses': ['Pyspark', 'Pandas', 'Python', 'MySQL'],
        'Fee'    : [5000, 3000, 8000, 6000],
        'Duration': ['30 days', '60 days', '90 days', '120 days']
    }

df = pd.DataFrame(techs)
df

   Courses   Fee  Duration
0  Pyspark  5000   30 days
1   Pandas  3000   60 days
2   Python  8000   90 days
3    MySQL  6000  120 days

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Courses   4 non-null      object
 1   Fee       4 non-null      int64
 2   Duration  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

In [17]:
# change data Types of dataframe columns
# astype()

types = {'Courses': str, 'Fee': int, 'Duration': str}
df = df.astype(types)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Courses   4 non-null      object
 1   Fee       4 non-null      int32
 2   Duration  4 non-null      object
dtypes: int32(1), object(2)
memory usage: 208.0+ bytes