In [20]:
import pandas as pd
import numpy as np

In [27]:

techs = {
        'Courses': ['Pyspark', 'Pandas', 'Python', 'MySQL'],
        'Fee'    : [5000, 3000, 8000, 6000],
        'Duration': ['30 days', '60 days', '90 days', '120 days']
    }

df = pd.DataFrame(techs)
df

   Courses   Fee  Duration
0  Pyspark  5000   30 days
1   Pandas  3000   60 days
2   Python  8000   90 days
3    MySQL  6000  120 days

In [9]:
# Get Shape of Pandas DataFrame

df.shape

(4, 3)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Courses   4 non-null      object
 1   Fee       4 non-null      int64
 2   Duration  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

In [6]:
# show columns of DataFrame

df.columns

Index(['Courses', 'Fee', 'Duration'], dtype='object')

In [23]:

# isna()  -  find missing values in DataFrame

df.isna().sum()

Courses     0
Fee         0
Duration    1
dtype: int64

In [26]:
# Filling missing values  - fillna()

df.fillna(0)

   Courses   Fee Duration
0  Pyspark  5000  30 days
1   Pandas  3000  60 days
2   Python  8000  90 days
3    MySQL  6000        0

In [ ]:
# Filling missing values - replace()