In [9]:
# DataFrame dropna() Usage 

import pandas as pd
import numpy as np

technologies= {
    'Courses':["Spark","PySpark","Hadoop","Python",np.nan],
    'Fee' :[22000,25000,23000,24000,np.nan],
    'Duration':['30days','50days','30days', None,np.nan],
    'Discount':[1000,2300,1000,1200,np.nan]
          }
df = pd.DataFrame(technologies)
print(df)

   Courses      Fee Duration  Discount
0    Spark  22000.0   30days    1000.0
1  PySpark  25000.0   50days    2300.0
2   Hadoop  23000.0   30days    1000.0
3   Python  24000.0     None    1200.0
4      NaN      NaN      NaN       NaN

In [10]:
df.isna().sum()

Courses     1
Fee         1
Duration    2
Discount    1
dtype: int64

In [11]:
# Drop rows that has all NaN values

df = df.dropna(how = 'all')
df

   Courses      Fee Duration  Discount
0    Spark  22000.0   30days    1000.0
1  PySpark  25000.0   50days    2300.0
2   Hadoop  23000.0   30days    1000.0
3   Python  24000.0     None    1200.0

In [12]:
df.isna().sum()

Courses     0
Fee         0
Duration    1
Discount    0
dtype: int64

In [13]:
df.assign(TutorAssigned = np.nan)

   Courses      Fee Duration  Discount  TutorAssigned
0    Spark  22000.0   30days    1000.0            NaN
1  PySpark  25000.0   50days    2300.0            NaN
2   Hadoop  23000.0   30days    1000.0            NaN
3   Python  24000.0     None    1200.0            NaN

In [15]:
# Drop columns that has all NaN values

df = df.dropna(how='all', axis = 1)
df

   Courses      Fee Duration  Discount
0    Spark  22000.0   30days    1000.0
1  PySpark  25000.0   50days    2300.0
2   Hadoop  23000.0   30days    1000.0
3   Python  24000.0     None    1200.0

In [19]:
# Default drop rows that contains nan values

df2=df.dropna()
df2

   Courses      Fee Duration  Discount
0    Spark  22000.0   30days    1000.0
1  PySpark  25000.0   50days    2300.0
2   Hadoop  23000.0   30days    1000.0

In [20]:
# Drop all columns with NaN values
df2=df.dropna(axis=1)
df2

   Courses      Fee  Discount
0    Spark  22000.0    1000.0
1  PySpark  25000.0    2300.0
2   Hadoop  23000.0    1000.0
3   Python  24000.0    1200.0

In [24]:
 # Drop rows that has NaN values on selected columns
    
df2=df.dropna(subset=['Courses','Duration'])
df2

   Courses      Fee Duration  Discount
0    Spark  22000.0   30days    1000.0
1  PySpark  25000.0   50days    2300.0
2   Hadoop  23000.0   30days    1000.0