In [86]:
import pandas as pd
import numpy as np

technologies= {
    'Courses':["Spark","PySpark","Hadoop","Python","Pandas"],
    'Fee' :[22000,25000,23000,24000,26000],
    'Duration':['30days','50days','30days', None,np.nan],
    'Discount':[1000,2300,1000,1200,2500]
          }
df = pd.DataFrame(technologies)
print(df)

   Courses    Fee Duration  Discount
0    Spark  22000   30days      1000
1  PySpark  25000   50days      2300
2   Hadoop  23000   30days      1000
3   Python  24000     None      1200
4   Pandas  26000      NaN      2500

In [87]:
df3 =df.query("Courses != 'Spark'")
df3

   Courses    Fee Duration  Discount
1  PySpark  25000   50days      2300
2   Hadoop  23000   30days      1000
3   Python  24000     None      1200
4   Pandas  26000      NaN      2500

In [88]:
# Query Rows using DataFrame.query()

df2=df.query("Courses == 'Spark'")
df2

  Courses    Fee Duration  Discount
0   Spark  22000   30days      1000

In [89]:
df

   Courses    Fee Duration  Discount
0    Spark  22000   30days      1000
1  PySpark  25000   50days      2300
2   Hadoop  23000   30days      1000
3   Python  24000     None      1200
4   Pandas  26000      NaN      2500

In [92]:
df4 = df.query("Courses in ('Spark','PySpark')")
df4

   Courses    Fee Duration  Discount
0    Spark  22000   30days      1000
1  PySpark  25000   50days      2300

In [93]:
df

   Courses    Fee Duration  Discount
0    Spark  22000   30days      1000
1  PySpark  25000   50days      2300
2   Hadoop  23000   30days      1000
3   Python  24000     None      1200
4   Pandas  26000      NaN      2500

In [94]:
# using df[] and loc[]

df.loc[df['Courses'] != 'Spark']

   Courses    Fee Duration  Discount
1  PySpark  25000   50days      2300
2   Hadoop  23000   30days      1000
3   Python  24000     None      1200
4   Pandas  26000      NaN      2500

In [96]:
df.loc[(df['Discount'] >= 1000) & (df['Discount'] <= 2000)]

  Courses    Fee Duration  Discount
0   Spark  22000   30days      1000
2  Hadoop  23000   30days      1000
3  Python  24000     None      1200

In [97]:
df.loc[(df['Discount'] >= 1200) & (df['Fee'] >= 23000 )]

   Courses    Fee Duration  Discount
1  PySpark  25000   50days      2300
3   Python  24000     None      1200
4   Pandas  26000      NaN      2500

In [105]:
df.loc[(df['Courses'] == 'Pandas') & (df['Discount'] >= 2200)]

  Courses    Fee Duration  Discount
4  Pandas  26000      NaN      2500