In [3]:
import pandas as pd

techs = {
        'Courses': ['Pyspark', 'Pandas', 'Python', 'MySQL'],
        'Fee'    : [5000, 3000, 8000, 6000],
        'Duration': ['30 days', '60 days', '90 days', '120 days']
    }

df = pd.DataFrame(techs)
df

   Courses   Fee  Duration
0  Pyspark  5000   30 days
1   Pandas  3000   60 days
2   Python  8000   90 days
3    MySQL  6000  120 days

In [4]:
# Select Rows by Index 

# iloc()
# loc()

df2 = df.iloc[2]
df2

Courses      Python
Fee            8000
Duration    90 days
Name: 2, dtype: object

In [5]:
# Select Rows by Index List

df2 = df.iloc[[1,0,2]]
df2

   Courses   Fee Duration
1   Pandas  3000  60 days
0  Pyspark  5000  30 days
2   Python  8000  90 days

In [6]:
# Select Last Row

df2 = df.iloc[-1]
df2

Courses        MySQL
Fee             6000
Duration    120 days
Name: 3, dtype: object

In [11]:
# Select First 2 Rows

df2 = df.iloc[:2]
df2

   Courses   Fee Duration
0  Pyspark  5000  30 days
1   Pandas  3000  60 days

In [21]:
# Select First 2 Rows and first two columns

df3 = df.iloc[:2, [0,1]]
df3

   Courses   Fee
0  Pyspark  5000
1   Pandas  3000

In [23]:


import numpy as np
technologies = {
    'Courses':["Spark","PySpark","Hadoop","Python","pandas","Oracle","Java"],
    'Fee' :[20000,25000,26000,22000,24000,21000,22000],
    'Duration':['30days','40days','35days','40days',np.nan,None,'55days'],
    'Discount':[1000,2300,1500,1200,2500,2100,2000]
               }
index_labels=['r1','r2','r3','r4','r5','r6','r7']
df = pd.DataFrame(technologies,index=index_labels)
print(df)

    Courses    Fee Duration  Discount
r1    Spark  20000   30days      1000
r2  PySpark  25000   40days      2300
r3   Hadoop  26000   35days      1500
r4   Python  22000   40days      1200
r5   pandas  24000      NaN      2500
r6   Oracle  21000     None      2100
r7     Java  22000   55days      2000

In [25]:
# loc[]  - Select Rows by Index Labels


df2 = df.loc['r7']
df2

Courses       Java
Fee          22000
Duration    55days
Discount      2000
Name: r7, dtype: object

In [26]:
df2 = df.loc[['r1', 'r3', 'r5']]
df2

   Courses    Fee Duration  Discount
r1   Spark  20000   30days      1000
r3  Hadoop  26000   35days      1500
r5  pandas  24000      NaN      2500