#### Pandas is a powerful Python library for data analysis and manipulation.

In [1]:
import pandas as pd
import numpy as np

#### Creating DataFrames from Dictionary

In [5]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago'],
        'ABC' : [1, 2, 3]
        },
        
        

df = pd.DataFrame(data)
print(df)

                    Name           Age                              City  \
0  [Alice, Bob, Charlie]  [25, 30, 35]  [New York, Los Angeles, Chicago]

         ABC
0  [1, 2, 3]

#### Creating DataFrames From List of Lists

In [6]:
data = [['Alice', 25, 'New York'],
        ['Bob', 30, 'Los Angeles'],
        ['Charlie', 35, 'Chicago']]

df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

#### From NumPy Array

In [139]:
array = np.array([[1, 2, 3], [4, 5, 6]])
df2 = pd.DataFrame(array, columns=['A', 'B', 'C'])
print(df2)

   A  B  C
0  1  2  3
1  4  5  6

#### Reading and Writing Data

In [ ]:
# df.to_csv('data.csv', index=False)

In [137]:
df2 = pd.read_csv('username.csv')
print(df)

  Username; Identifier;First name;Last name
0               booker12;9012;Rachel;Booker
1                    grey07;2070;Laura;Grey
2              johnson81;4081;Craig;Johnson
3               jenkins46;9346;Mary;Jenkins
4                  smith79;5079;Jamie;Smith

#### Viewing and Inspecting Data

In [142]:
print("============First 5 rows of the DataFrame:================")
print(df.head())  # First 5 rows
print("===============Last 5 rows of the DataFrame:============")
print(df.tail())  # Last 5 rows
print("===============summary of the DataFrame:==========")
print(df.info())  # Summary

print('==========Summary statistics================')

print(df.describe())  # Summary statistics
print("========DataFrame shape ====================")
print(df.shape)  # (rows, columns)
print("========DataFrame columns ==================")
print(df.columns)  # Column names
print(df.index)  # Row indices
print("==========Data types =====================")
df.dtypes        # data types

============First 5 rows of the DataFrame:================
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
===============Last 5 rows of the DataFrame:============
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
===============summary of the DataFrame:==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
==========Summary statistics================
        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0
========DataFrame shape ====================
(3, 3)
========DataFrame columns ==================
Index(['Name', 'Age', 'City'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
==========Data types =====================

Name    object
Age      int64
City    object
dtype: object

#### Selecting Columns

In [143]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago'],
        'Salary': [70000, 80000, 90000],
        'ABC' : [1, 2, 3]
        }

df = pd.DataFrame(data)

print(df['Name'])  # Single column
print(df[['Name', 'Age']])  # Multiple columns

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

##### Selecting Rows

#### .loc[] → Label-based indexing

#### .iloc[] → Integer-based indexing

In [11]:

print("First row (by index)")
print(df.iloc[0])  # First row (by index)

First row (by index)
Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [10]:
print(df.loc[0])  # First row (by label)

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [ ]:
df.iloc[0, 0] # First row, first column (by index)

df.iloc[:, 2]  # All rows, third column (by index)

0       New York
1    Los Angeles
2        Chicago
Name: City, dtype: object

### conditional filtering

In [144]:
df[df['Age'] > 25]         # conditional filtering

      Name  Age         City  Salary  ABC
1      Bob   30  Los Angeles   80000    2
2  Charlie   35      Chicago   90000    3

##### Sorting Data

In [62]:
df.sort_values(by='Age')     # sort by column
                
# df.sort_values(by=['col1', 'col2'], ascending=[True, False])

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

Missing Data Handling

In [ ]:
df.isnull()                     # detect missing values
df.isna()                      # detect missing values  

df.notnull()
df.dropna()                    # drop rows with any NA
df.dropna(how='any')  # drop if any NaN

nan_df = df[df.isna().any(axis=1)]  # axis=1 means we’re checking across columns for each row.

all_data = df.dropna(how='all') # drop rows where all elements are NA

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

### Renaming / Replacing

In [106]:
# df.rename(columns={'old': 'new'}, inplace=True)

df.rename(columns={'Age': 'student_Age'}, inplace=True)
print(df)

      Name  student_Age         City  Salary  ABC
0    Alice           25     New York   70000    1
1      Bob           30  Los Angeles   80000    2
2  Charlie           35      Chicago   90000    3

#####  Dropping Rows / Columns

In [149]:
df.drop('ABC', axis=1, inplace = True)     # drop column 'ABC'

# df.drop(['col1', 'col2'], axis=1)

# df.drop(index=0, inplace = True)  # Remove first row

#### Adding Columns

In [150]:
df['Experience'] = [5, 8, 12]  # Adding column
print(df)

      Name  Age         City  Salary  Experience
0    Alice   25     New York   70000           5
1      Bob   30  Los Angeles   80000           8
2  Charlie   35      Chicago   90000          12

##### Concatenating (pd.concat)

##### Adding new rows or columns to a dataset.

##### DataFrames have same columns (vertical stack) or same index (horizontal stack).

In [3]:
import pandas as pd

df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

# Vertically concatenate
result_v = pd.concat([df1, df2], axis=0, ignore_index=True)

print("Result of vertical concatenation:")
print(result_v)

# Horizontally concatenate
result_h = pd.concat([df1, df2], axis=1)
print("Result of horizontal concatenation:")
print(result_h)

Result of vertical concatenation:
   A  B
0  1  3
1  2  4
2  5  7
3  6  8
Result of horizontal concatenation:
   A  B  A  B
0  1  3  5  7
1  2  4  6  8

#### GroupBy and Aggregation

##### Aggregation means applying a mathematical function to summarize data. It can be used to get a summary of columns in our dataset like getting sum, minimum, maximum etc.

##### sum()         : Compute sum of column values in each column
##### min()          : Compute min of column values
##### max()         : Compute max of column values
##### mean()       : Compute mean of column

In [118]:
df = pd.DataFrame([[9, 4, 8, 9],
                   [8, 10, 7, 6],
                   [7, 6, 8, 5]],
                  columns=['Maths',  'English', 
                           'Science', 'History'])

print(df)

   Maths  English  Science  History
0      9        4        8        9
1      8       10        7        6
2      7        6        8        5

In [120]:
#  sum() 

print(df.sum())  # sum of each column

Maths      24
English    20
Science    23
History    20
dtype: int64

In [121]:
# describe()

df.describe() # summary statistics

       Maths    English   Science   History
count    3.0   3.000000  3.000000  3.000000
mean     8.0   6.666667  7.666667  6.666667
std      1.0   3.055050  0.577350  2.081666
min      7.0   4.000000  7.000000  5.000000
25%      7.5   5.000000  7.500000  5.500000
50%      8.0   6.000000  8.000000  6.000000
75%      8.5   8.000000  8.000000  7.500000
max      9.0  10.000000  8.000000  9.000000

In [122]:
# agg()

df.agg(['sum', 'min', 'max'])   # apply multiple functions

     Maths  English  Science  History
sum     24       20       23       20
min      7        4        7        5
max      9       10        8        9

#### Grouping in Pandas :   groupby('column')

##### Grouping in Pandas means organizing your data into groups based on some columns.

In [126]:
import pandas as pd

# small bakery order dataset
data = {
    'Item': ['Cake', 'Cake', 'Bread', 'Pastry', 'Cake'],
    'Flavor': ['Chocolate', 'Vanilla', 'Whole Wheat', 'Strawberry', 'Chocolate'],
    'Price': [250, 220, 80, 120, 250]
}

df = pd.DataFrame(data)
print(df)

     Item       Flavor  Price
0    Cake    Chocolate    250
1    Cake      Vanilla    220
2   Bread  Whole Wheat     80
3  Pastry   Strawberry    120
4    Cake    Chocolate    250

In [125]:
grouped = df.groupby('Item')    # Group by 'Item' column
print(grouped)      #  it just creates a grouped object

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000022928129750>

In [128]:
#  output shows the total earnings from each item

print(df.groupby('Item')['Price'].sum()) # the total price of each item sold:

Item
Bread      80
Cake      720
Pastry    120
Name: Price, dtype: int64

In [129]:
# Grouping by Multiple Columns

print(df.groupby(['Item', 'Flavor'])['Price'].sum())

Item    Flavor
Bread   Whole Wheat     80
Cake    Chocolate      500
        Vanilla        220
Pastry  Strawberry     120
Name: Price, dtype: int64

##### concat()

In [131]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)

frames = [df1, df2]

result = pd.concat(frames)
print(result)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

#### Drop Duplicate Rows

In [ ]:
df.drop_duplicates(inplace=True)